### ISSUE TITLE
Bridges

### ISSUE THREAD

**Issue by everkerke** [seth127/MundusCentrum#6]
Where are the bridges on the map? How do we display them?  How do we record building bridges, destroying bridges? Can the updated bridge state then impact legal moves?

- Sappers
- Build bridge
- Destroy bridge
- Impact on legal movement

**Comment by seth127** [comment]
Starting bridges are here, per @grizzzzzz email on 8/1/21

```
Between Lune Valley and Tower Hills -- A2 - A5
The Shire and Buckland -- A7 - B9
Weather Hills and Rhudaur -- B8 - B6
Rhudaur and Eregion -- B6 - E2
Carrock and Anduin Valley -- C1 - C3
North Mirkwood and Eastern Mirkwood -- C2 - C4
North Mirkwood and Esgaroth -- C2 - D3
South Rhun and Brown Lands -- D4 - F5
Anduin Valley and Gladden Fields -- C3 - F2
Minhiriath and Dunland -- E1 - E3
Minhiriath and Enedwaith -- E1 - E4
Eregion and Dunland -- E2 - E3
Enedwaith and Gap of Rohan -- E4 - E7
Gap of Rohan and The Wold -- E7 - F4
The Wold and Emyn Muil -- F4 - F7
Minas Tirith and Ithilien -- G7 - G8
Harondor and Harad -- I1 - I3
```

**Comment by seth127** [comment]
remember to add bridges to here too https://github.com/seth127/MundusCentrum/blob/main/R/draw-map.R#L114

**Comment by seth127** [comment]
Code pushed here https://github.com/seth127/MundusCentrum/commit/a2c233287de7499b38186d47ee8705d9bb46cc65
